# Generated by Django 4.0.6 on 2022-07-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VPNClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='VPN Client name')),
                ('client_email', models.CharField(max_length=255, verbose_name='VPN Client email')),
            ],
        ),
        migrations.CreateModel(
            name='VPNServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255, verbose_name='Hostname')),
                ('public_ip', models.CharField(max_length=15, verbose_name='Server IP')),
                ('if_name', models.CharField(max_length=50, verbose_name='Eth interface name')),
            ],
        ),
        migrations.CreateModel(
            name='VPNService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255, verbose_name='VPN Service name')),
                ('vpn_network', models.CharField(max_length=18, verbose_name='VPN Service network')),
                ('vpn_port', models.IntegerField(verbose_name='VPN port')),
                ('private_ip', models.CharField(max_length=15, verbose_name='VPN Service ip')),
                ('public_key', models.CharField(max_length=44, verbose_name='VPN Service pubkey')),
                ('private_key', models.CharField(max_length=44, verbose_name='VPN Service privkey')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vpnserver', verbose_name='VPN server')),
            ],
        ),
        migrations.CreateModel(
            name='VPNDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=255, verbose_name='VPN Device name')),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('sm', 'Smartphone')], max_length=10, verbose_name='VPN Device type')),
                ('private_ip', models.CharField(max_length=15, verbose_name='VPN Device ip')),
                ('public_key', models.CharField(max_length=44, verbose_name='VPN Device pubkey')),
                ('private_key', models.CharField(max_length=44, verbose_name='VPN Device privkey')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vpnclient', verbose_name='VPN Client')),
            ],
        ),
        migrations.AddField(
            model_name='vpnclient',
            name='vpn_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.vpnservice', verbose_name='VPN Service'),
        ),
    ]
