# Generated by Django 4.0.6 on 2022-07-13 10:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_vpnservice_vpn_if_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpndevice',
            name='private_ip',
            field=models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address], verbose_name='VPN Device ip'),
        ),
        migrations.AlterField(
            model_name='vpnserver',
            name='public_ip',
            field=models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address], verbose_name='Server IP'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='private_ip',
            field=models.CharField(max_length=15, validators=[django.core.validators.validate_ipv4_address], verbose_name='VPN Service ip'),
        ),
    ]
