# Generated by Django 4.0.6 on 2022-07-14 09:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_vpnclient_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpndevice',
            name='allowed_ips',
            field=models.CharField(default='0.0.0.0/0', max_length=255, verbose_name='Allowed ips'),
        ),
        migrations.AddField(
            model_name='vpndevice',
            name='dns',
            field=models.CharField(default='8.8.8.8', max_length=15, validators=[django.core.validators.validate_ipv4_address], verbose_name='DNS ip'),
        ),
        migrations.AddField(
            model_name='vpndevice',
            name='ka_check',
            field=models.IntegerField(default=20, verbose_name='Keepalive check interval'),
        ),
        migrations.AlterField(
            model_name='vpndevice',
            name='private_key',
            field=models.CharField(default='qI0m7a8AKyc77+htvY6aP4H2KJuviBUKm3Lfi+fAWlU=', max_length=44, verbose_name='VPN Device privkey'),
        ),
        migrations.AlterField(
            model_name='vpndevice',
            name='public_key',
            field=models.CharField(default='999UpWiLZj8Q0Xleg/e38NAFphWc2xwkPE8nOkSZQCI=', max_length=44, verbose_name='VPN Device pubkey'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='private_key',
            field=models.CharField(default='YnijlxENkT4YWai8QwnUXhIi9MmLIkVcQ48H1fPq5mI=', max_length=44, verbose_name='VPN Service privkey'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='public_key',
            field=models.CharField(default='cLlOTQXDY7i3hlEY2cH+cxGhz9iZB9qIH/LRyIKGWFU=', max_length=44, verbose_name='VPN Service pubkey'),
        ),
    ]
