# Generated by Django 4.0.6 on 2022-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_vpndevice_allowed_ips_vpndevice_dns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpndevice',
            name='private_key',
            field=models.CharField(max_length=44, verbose_name='VPN Device privkey'),
        ),
        migrations.AlterField(
            model_name='vpndevice',
            name='public_key',
            field=models.CharField(max_length=44, verbose_name='VPN Device pubkey'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='private_key',
            field=models.CharField(default='UL2DO2J6KOKUKgF5wtcr01+KHmd+V+llDSEKI+SC62w=', max_length=44, verbose_name='VPN Service privkey'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='public_key',
            field=models.CharField(default='KAhkNncPUOSHEhGruxNnfQ1OIut76FruLXB/ykLXokQ=', max_length=44, verbose_name='VPN Service pubkey'),
        ),
    ]
