# Generated by Django 4.0.6 on 2022-07-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_alter_vpndevice_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnservice',
            name='private_key',
            field=models.CharField(max_length=44, verbose_name='VPN Service privkey'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='public_key',
            field=models.CharField(max_length=44, verbose_name='VPN Service pubkey'),
        ),
    ]
