# Generated by Django 4.0.6 on 2022-07-18 05:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_alter_vpnservice_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnserver',
            name='hostname',
            field=models.CharField(max_length=255, unique=True, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='vpnserver',
            name='public_ip',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.validate_ipv4_address], verbose_name='Server IP'),
        ),
        migrations.AlterField(
            model_name='vpnservice',
            name='service_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='VPN Service name'),
        ),
    ]
